### PR TITLE
added placeholder instead of broken image in the product catalog

### PR DESCRIPTION
**Pull request by ImmortalF**
#3 
added placeholder instead of broken image in the product catalog
issue fixed
image

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks ImmortalF, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by ImmortalF** [comment]
The result
image

**Comment by ImmortalF** [comment]
@vanessa-cooper

**Review by vanessa-cooper — APPROVED** [review]
Excellent job ImmortalF! You're now able to merge the PR.

**Pull request merged**
